# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := ReadWriteDemo
ARDUINO_LIBS := EpoxyMockDigitalWriteFast AceCommon AceWire
include ../../../EpoxyDuino/EpoxyDuino.mk
